specVersion: "0.3.0"

name: "subqlstarter-terra"
version: "0.0.0"
description: ""
repository: "https://github.com/stwiname/subqlstarter-terra"

schema:
  file: "./schema.graphql"

network:
  genesisHash: 'q4PIUU/W6KSxGM9wyowkSW+Ij8HuODDeM4USpA2ucWc='
  endpoint: 'https://terra.stakesystems.io'
  chainId: 'columbus-5'

dataSources:
  - kind: terra/Runtime
    startBlock: 6747920
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleBlock
          kind: terra/BlockHandler
        - handler: handleTransaction
          kind: terra/TransactionHandler
        - handler: handleMessage
          kind: terra/MessageHandler
          filter:
            type: '/cosmos.bank.v1beta1.MsgSend'
        - handler: handleEvent
          kind: terra/EventHandler
          filter:
            type: transfer
